export const stories = [
  {
    id: 1,
    slug: 'adewale-from-the-streets-to-the-pitch',
    name: 'Adewale Ogundimu',
    age: 17,
    team: 'Lagos FC',
    program: 'Elite & Exposure Program',
    image: '/story-adewale.webp',
    excerpt: 'From playing barefoot on dusty streets in Ibadan to earning a trial with a professional club — Adewale\'s journey is what TFP is all about.',
    story: `Adewale Ogundimu never owned a proper pair of football boots until he joined TFP at age 14. Growing up in a modest household in Ibadan, football was his escape — played barefoot on dusty streets with a half-deflated ball.\n\nWhen his school teacher recommended him for TFP's Grassroots Program in 2023, nobody could have predicted what would follow. Within six months, his natural talent was undeniable. His first touch, his vision, his reading of the game — Coach Emeka Obi knew immediately he was special.\n\nBy Season 2, Adewale had moved into the Rising Players Program. His performances in the league were outstanding — 12 goals and 8 assists in a single season. Parents on the sidelines would stop and watch whenever he had the ball.\n\nIn 2025, Adewale was selected as one of three TFP players invited to a professional club trial in Lagos. He didn't just attend — he impressed. Today, Adewale is in conversations with the club's youth academy.\n\n"TFP gave me boots, coaching, and belief," he says. "Before TFP, I didn't think this was possible for someone like me."`,
    date: '2026-06-10',
    category: 'Player Story',
    tags: ['Elite Program', 'Trial', 'Success Story'],
  },
  {
    id: 2,
    slug: 'chukwuemeka-the-goalkeeper-who-refused-to-quit',
    name: 'Chukwuemeka Nwosu',
    age: 16,
    team: 'Enugu Warriors',
    program: 'Rising Players Program',
    image: '/story-2.webp',
    excerpt: 'After two rejected trials at other academies, Chukwuemeka found his home at TFP — and has not conceded a single goal in his last 8 matches.',
    story: `Chukwuemeka Nwosu was rejected twice before he found TFP. Two different academies told him he was too small, too quiet, not good enough. At 14, he almost gave up football entirely.\n\nHis older brother drove him three hours from Enugu to Oyo State for a TFP trial. Coach Seun Bello saw something different — not just ability, but character. "He had a fire behind his eyes," Coach Bello recalls. "That's not something you can teach."\n\nUnder Coach Bello's specialist goalkeeping program, Chukwuemeka transformed. His positioning improved dramatically. His communication with defenders became commanding. His shot-stopping became the stuff of legend within the league.\n\nIn the 2025 season, Chukwuemeka kept 8 consecutive clean sheets — a TFP record. Enugu Warriors went on to finish second in the standings, with their goalkeeper as the undisputed star.\n\n"They told me I wasn't good enough," Chukwuemeka says. "TFP told me I was. That's the difference."`,
    date: '2026-06-05',
    category: 'Player Story',
    tags: ['Goalkeeper', 'Resilience', 'Rising Players'],
  },
  {
    id: 3,
    slug: 'tunde-scoring-goals-and-passing-exams',
    name: 'Tunde Fashola',
    age: 15,
    team: 'Ibadan United',
    program: 'Rising Players Program',
    image: '/story-3.webp',
    excerpt: 'Top scorer in the TFP league and top of his class at school — Tunde proves that football and education can go hand in hand.',
    story: `When Tunde Fashola's parents enrolled him in TFP, they had one condition — his grades could not drop. His mother, a schoolteacher in Ibadan, was supportive of his football dreams but firm about education.\n\nTFP's flexible training schedule made it possible. Morning sessions before school. Weekend matches. Structured rest days. Tunde never missed a class and never missed a training session.\n\nThe results spoke for themselves. In the 2025 season, Tunde finished as the league's top scorer with 15 goals. That same term, he scored straight A's in his school examinations.\n\n"People think football and school can't work together," Tunde says. "TFP showed my parents that they can. Now they're my biggest supporters at every match."\n\nTunde's story has become one of TFP's most powerful testimonials — proof that the organization's commitment to education is not just a tagline, but a lived reality for its players.`,
    date: '2026-05-28',
    category: 'Player Story',
    tags: ['Education', 'Top Scorer', 'Balance'],
  },
];
